// <auto-generated />
using GPDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GPDAL.Migrations
{
    [DbContext(typeof(GPDbContext))]
    [Migration("20181115074656_GPdbintial")]
    partial class GPdbintial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GPBOL.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoalName");

                    b.HasKey("GoalId");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("GPBOL.GPUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<int>("Age");

                    b.Property<string>("FullName");

                    b.Property<string>("Gender");

                    b.Property<string>("Password");

                    b.Property<string>("UserEmail");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GPBOL.GPWorkout", b =>
                {
                    b.Property<string>("Id");

                    b.Property<int>("BMI");

                    b.Property<int>("GoalId");

                    b.Property<int>("Height");

                    b.Property<bool>("IsApproved");

                    b.Property<int>("Weight");

                    b.Property<int>("WorkId");

                    b.Property<string>("WorkoutDescription");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GPworkout");
                });

            modelBuilder.Entity("GPBOL.GPWorkout", b =>
                {
                    b.HasOne("GPBOL.Goal", "Goal")
                        .WithMany("GPWorkouts")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GPBOL.GPUser", "User")
                        .WithMany("GPWorkouts")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
